SELECT P.ProductID,
       P.Name, 
       D.OrderQty 

FROM Sales.SalesOrderDetail AS D
RIGHT OUTER JOIN Production.Product AS P 
ON D.ProductID = P.ProductID;  


--RIGHT OUTER JOIN DEVUEVE TODOS LOS REGISTROS DE LA TABLA DERECHA (TABLA SECUNDARIA) Y LOS REGITROS COINCIDIENT4ES DE LA TABLA IZQUIERDA (SI LOS HAY)
